# Generated by Django 3.1.3 on 2020-12-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
