# Generated by Django 3.1.3 on 2020-12-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_auto_20201205_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='image',
            new_name='img',
        ),
    ]
