# Generated by Django 3.1.3 on 2020-12-10 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='desc',
            new_name='desc2',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='img',
            new_name='img2',
        ),
    ]
