# Generated by Django 3.1.3 on 2020-12-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_auto_20201210_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='heading',
            new_name='head',
        ),
    ]
