# Generated by Django 3.1.3 on 2020-12-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0008_auto_20201211_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='desc2',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='img2',
            new_name='img',
        ),
    ]
